---
flexpart_directory_definitions:
  - path: "{{ flexpart_install_dir }}"
    mode: "0755"
  - path: "{{ flexpart_install_dir }}/config"
    mode: "0750"
  - path: "{{ flexpart_install_dir }}/scripts"
    mode: "0755"
  - path: "{{ flexpart_install_dir }}/examples/reference-case"
    mode: "0755"
  - path: "{{ flexpart_data_dir }}"
    mode: "0750"
  - path: "{{ flexpart_data_dir }}/input"
    mode: "0750"
  - path: "{{ flexpart_data_dir }}/work"
    mode: "0750"
  - path: "{{ flexpart_data_dir }}/output"
    mode: "0750"
  - path: "{{ flexpart_log_dir }}"
    mode: "0750"
