---
flexpart_directory_definitions:
  - path: "{{ flexpart_install_dir }}"
    mode: "0755"
  - path: "{{ flexpart_install_dir }}/src"
    mode: "0755"
  - path: "{{ flexpart_config_dir }}"
    mode: "0750"
  - path: "{{ flexpart_data_dir }}"
    mode: "0770"
  - path: "{{ flexpart_meteorology_dir }}"
    mode: "0770"
  - path: "{{ flexpart_run_dir }}"
    mode: "0770"
  - path: "{{ flexpart_plot_dir }}"
    mode: "0770"
  - path: "{{ flexpart_log_dir }}"
    mode: "0770"
