---
docker_apt_architecture_map:
  x86_64: amd64
  aarch64: arm64
  armv7l: armhf

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

docker_redhat_repository_url: https://download.docker.com/linux/rhel/docker-ce.repo

docker_redhat_conflicting_packages:
  - docker
  - docker-client
  - docker-client-latest
  - docker-common
  - docker-latest
  - docker-latest-logrotate
  - docker-logrotate
  - docker-engine
  - podman
  - runc
